### ISSUE TITLE
(re-/mis-)Appropriate an existing Unicode character to represent the currency.

### ISSUE THREAD

**Issue by nathan-at-least** [Electric-Coin-Company/zcash#104]
If we bless usage of an existing Unicode character early we might have consistent use and adoption.  To do this well, we should ensure we select a character whose existing usage contexts would be as least likely to interact with cryptocurrencies as possible. Also, it should look cool.

Note: This is a separate task than lobbying for a new unicode symbol, which may also be a longer term goal.

Related: [Bitcoin Symbol wiki page](https://en.bitcoin.it/wiki/Bitcoin_symbol), #99, #103

**Comment by daira** [comment]
@zookozcash has been using ⓩ in blog posts; I like it and think we should stick with it.

**Comment by daira** [comment]
Bitcoin got their symbol included in Unicode: http://www.unicode.org/L2/L2015/15229-bitcoin-sign.pdf
