### ISSUE TITLE
What was the purpose of the commented out PoW-style loop in chainparams.cpp?

### ISSUE THREAD

**Issue by nathan-at-least** [Electric-Coin-Company/zcash#106]
Paging @imichaelmiers,

We noticed a strange loop in [the ``CRegTestParams`` constructor](https://github.com/Electric-Coin-Company/zerocashd/blob/get_being_strange-0.9.4-1/src/chainparams.cpp#L242).

What was the purpose of this loop? Is it related to the commented out hash assertions? Does the genesis block require a valid proof of work?

**Comment by nathan-at-least** [comment]
We understand ``chainparams.cpp`` and the need for valid nonces in the genesis blocks of the different network configs now.

**Comment by imichaelmiers** [comment]
Is there a ticket opened to make those changes?

**Comment by ebfull** [comment]
@imichaelmiers 

That was already done: https://github.com/Electric-Coin-Company/zcash/commit/8505fd548a8547f06d45a019328349f20ced26a5

**Comment by imichaelmiers** [comment]
@ebfull  Right. So that looks to me like its the short term one.  There's still a long term one for setting up peer discover and everything where we don't have a single point of failure. Not something we need to do now, but something we need to track.

**Comment by ebfull** [comment]
@imichaelmiers #630
