### ISSUE TITLE
Link to existing code / conversations / tickets upstream for hard-fork detection.

### ISSUE THREAD

**Issue by nathan-at-least** [Electric-Coin-Company/zcash#109]
I recall a thread where people mentioned a hard-fork detection mechanism in bitcoin-development. I should link to that conversation, then go hunt for the code they're alluding to, and once those links are in place, file any new relevant tickets and close this one.

**Comment by ebfull** [comment]
This is one of *those* issue titles. Let's bring the discussion over to #131.
