### ISSUE TITLE
Read the Bitcoin Developer's Guide

### ISSUE THREAD

**Issue by nathan-at-least** [Electric-Coin-Company/zcash#116]
The engineers should all read the [Bitcoin Developer Guide](https://bitcoin.org/en/developer-guide) for general background.

I'm assigning this to myself, and once I've finished, I'll reassign to @daira unless she's commented here that she's already read it. After that, we can close this task.

**Comment by ebfull** [comment]
Can we consider closing this?

**Comment by daira** [comment]
I will read it now.
