### ISSUE TITLE
Ensure consensus code restricts vpub_old in Pour operations to conserve currency units.

### ISSUE THREAD

**Issue by nathan-at-least** [Electric-Coin-Company/zcash#267]
We need to ensure consensus code invalidates any transaction containing a Protect operation where the amount doesn't balance.

To test this, let's create Protects with a larger value than the underlying clear-coin, and then test two critical cases:

* ensure ``AcceptToMemoryPool`` rejects it.
* ensure that a block containing the malicious/invalid transaction is rejected from verifying blocks.

Then, of course, ensure that the normal system test process of creating a valid Protect still functions correctly (and the result can be successfully Poured).

**Comment by daira** [comment]
The description of this issue is obsolete because we no longer have Protects. I think the same issue might apply to Pours, though.

**Comment by ebfull** [comment]
I am pretty certain all the cases mentioned here are tested by our rpc tests, but I would hestitate closing this until those tests are automatically executed by buildbot.

**Comment by nathan-at-least** [comment]
Running RPC tests in buildbot is #492, so let's close this when #492 closes.

I'm removing 'needs prioritization' since this depends solely on #492 now.

**Comment by defuse** [comment]
Buildbot is testing the RPC now, so if #492 is closable then this is closable.

**Comment by defuse** [comment]
#492 is closed now so we can close this now.
