### ISSUE TITLE
specify external formats for Zcash private keys and Zcash public addresses

### ISSUE THREAD

**Issue by daira** [Electric-Coin-Company/zcash#274]
There should be byte-string and text (e.g. base32 or similar) formats for Zcash private keys and for Zcash public addresses.

Note: the terminology for these is not yet decided. Provisionally we have "protected" and "traceable" (formerly "basecoin") transactions and addresses, so the terminology for keys needs to fit in with that (see #74).

**Comment by ebfull** [comment]
I think this is becoming specified, which is nice, but until we implement it I won't be confident in the specification. Also, we can't really implement it until we switch to crypto_box. (#558).

**Comment by daira** [comment]
I think this is adequately specified by the current protocol spec (or by https://github.com/Electric-Coin-Company/zips/pull/5 if the crypto_box proposal is accepted).
