### ISSUE TITLE
Create automated test which asserts Verify fails when serial numbers collide for distinct coins.

### ISSUE THREAD

**Issue by nathan-at-least** [Electric-Coin-Company/zcash#51]
<a href="https://github.com/nathan-at-least"><img src="https://avatars.githubusercontent.com/u/4369700?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [nathan-at-least](https://github.com/nathan-at-least)**
_Sunday Dec 07, 2014 at 00:06 GMT_
_Originally opened as https://github.com/Electric-Coin-Company/libzerocash/issues/14_

----

This test should pass only when `Verify` is augmented to protect against this attack vector.  (Note: we also should attempt to ensure any change to `Verify` matches any changes to the formal security analysis, although we may not want to block on that.)

**Comment by ebfull** [comment]
There are many tests for this behavior in the test suite currently.
