### ISSUE TITLE
Investigate using "application specific salting" for ``CRH`` and ``PRF`` instantiations.

### ISSUE THREAD

**Issue by nathan-at-least** [Electric-Coin-Company/zcash#53]
<a href="https://github.com/nathan-at-least"><img src="https://avatars.githubusercontent.com/u/4369700?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [nathan-at-least](https://github.com/nathan-at-least)**
_Monday Dec 08, 2014 at 04:20 GMT_
_Originally opened as https://github.com/Electric-Coin-Company/libzerocash/issues/16_

----

Is it worth adding high-entropy "application-specific salts" to any of the CRH or PRFs in zerocash?

(My hunch is: no, because every PRF or CRH input is already highly entropic.  This ticket is just to remind me to re-read over each of the inputs and ask if this assumption is justified.)

In `tahoe-lafs`, some hash functions use "application specific salting", which I believe is similar to the "personal" field of the blake2 hash API.

Imagine a world where some adversaries have very very large rainbow tables, and they grow continually.  As these grow over time, more and more preimages will be aggregated.  If an adversary with access to such a rainbow table sees an image (output) which happens to correspond to an entry in their table, they have learned the preimage (input).

If the inputs are already guaranteed to be high-entropy, this isn't a very large concern.

If the inputs may be low entropy, by using a public global application-specific salt, this adds some cost to the giant-rainbow-table-in-the-sky because it must have a special case for the target application.

**Comment by ebfull** [comment]
@daira Would you like to reconsider this in light of the protocol spec work?

**Comment by daira** [comment]
I looked over all the hashes in the protocol, and concluded that there were none that do not already have an input entropy of at least 256 bits (relative to the knowledge of an attacker who constructs a rainbow table that is independent of particular address keys, transactions, or treestates). I'll maintain this property over any protocol changes.
