### ISSUE TITLE
Rename ``./qa/zerocash`` to ``./qa/zcash`` and update buildbot to match.

### ISSUE THREAD

**Issue by nathan-at-least** [Electric-Coin-Company/zcash#546]

**Comment by defuse** [comment]
Doing this

**Comment by defuse** [comment]
PR in #692 to rename the folder. I already changed the buildbot config so someone should review that.

Here's a build using the old folder name and new buildbot config to test backwards-compatibility: http://ci.leastauthority.com:8010/builders/zcash/builds/56

Whoever reviews this should start a test of that pull request; I don't know how to do that currently (we urgently need #634 done!!!)

**Comment by defuse** [comment]
Tests pass, closing.
