### ISSUE TITLE
assertion failure in bitcoind at db/version_set.cc:803

### ISSUE THREAD

**Issue by daira** [Electric-Coin-Company/zcash#59]
After working around the problem in #56 , running ``bitcoind`` results in this error:
```
: Error loading block database.

Do you want to rebuild the block database now?
bitcoind: db/version_set.cc:803: leveldb::VersionSet::~VersionSet(): Assertion `dummy_versions_.next_ == &dummy_versions_' failed.
Aborted
```

**Comment by ebfull** [comment]
I remember fixing this bug last year, it was a bug in the undo system. (I don't think we were properly serializing those entries.)

Anyway, this ticket is obsolete.
