### ISSUE TITLE
zcutil/fetch-params.sh fails on OS X because sha256sum is missing

### ISSUE THREAD

**Issue by twitched** [Electric-Coin-Company/zcash#638]
When verifying the downloaded params, fetch-params.sh fails because sha256sum is missing on OS X.

output:

	Verifying parameter file integrity via sha256sum...
	./zcutil/fetch-params.sh: line 76: sha256sum: command not found

**Comment by twitched** [comment]
Sorry, just saw that zcash is only supposed to work on Linux.

**Comment by ebfull** [comment]
I wonder what the sha256sum utility is called on OS X? `sha256`?

**Comment by twitched** [comment]
`shasum -a 256`
