### ISSUE TITLE
Put the alpha parameters on S3

### ISSUE THREAD

**Issue by defuse** [Electric-Coin-Company/zcash#639]

**Comment by defuse** [comment]
https://s3.amazonaws.com/zcashalpha/zc-testnet-public-alpha-proving.key
https://s3.amazonaws.com/zcashalpha/zc-testnet-public-alpha-verification.key

Now make the website `downloads/` thing redirect to those URLs.

**Comment by ebfull** [comment]
Done.

**Comment by defuse** [comment]
Awesome! I just downloaded the whole proving key in 7 minutes.
