### ISSUE TITLE
Build Issue

### ISSUE THREAD

**Issue by squawka99** [Electric-Coin-Company/zcash#643]
Debian Jessie 64bit

./zcutil/build.sh from the Public Alpha guide results in the following error

make: Leaving directory '/home/user/zcash/depends'
+ ./autogen.sh
./autogen.sh: 9: ./autogen.sh: autoreconf: not found

**Comment by ebfull** [comment]
You need to install autotools. Here's a few dependencies to get you started:

```
sudo apt-get install build-essential libtool autotools-dev automake pkg-config libssl-dev libevent-dev bsdmainutils

```

(taken from `build-unix.md`)

**Comment by squawka99** [comment]
New install of debian and I didn't have autoreconf installed.

sudo apt-get install dh-autoreconf

Fixed the issue
