### ISSUE TITLE
Update site to explain differences w/ other privacy-focused coins?

### ISSUE THREAD

**Issue by jprichardson** [Electric-Coin-Company/zcash#650]
Hi! Congrats on publicly launching Zcash. Would you be willing to update your main site so as to communicate the value proposition of Zcash to Dash, Monero, and ShadowCash? Thanks!

**Comment by ebfull** [comment]
[FAQ answers this question for now.](https://github.com/Electric-Coin-Company/zcash/wiki/FAQ#q-how-does-zcash-compare-to-x-financial-privacy-technology) The basic answer is: we'll make a blog post about it as soon as we can.
