### ISSUE TITLE
Bring back the apt-get install dependency command to the documentation

### ISSUE THREAD

**Issue by defuse** [Electric-Coin-Company/zcash#655]
There are some dependencies that don't come from the depends system. We used to have a documented `apt-get install ...` command that installed these, but it was deleted. Bring it back by adding it to the public alpha guide.

(at least one alpha tester's build failed because this step was missing from our documentation)

**Comment by defuse** [comment]
Thanks mappum on IRC.

**Comment by defuse** [comment]
I added the apt-get command back to the public alpha guide.

**Comment by ebfull** [comment]
LGTM
