### ISSUE TITLE
how to connect to irc.oftc.net without revealing my IP address?

### ISSUE THREAD

**Issue by petjal** [Electric-Coin-Company/zcash#662]
Tried to use tor-browser-bundle 

>https://www.torproject.org/download/download-easy.html.en

to go here:

>https://webchat.oftc.net/?channels=zchat

but got

>[00:43] == ERROR: Anonymous TOR usage is unavailable

**Comment by neuhaus** [comment]
OFTC allows Tor according to http://www.oftc.net/Tor/
I guess you have to a native IRC client to connect via tor instead of using their web client.

**Comment by nathan-at-least** [comment]
The OFTC network has a [page on Tor support](http://www.oftc.net/Tor/), so I'll close this ticket assuming that page is sufficient.  If not, please open a new ticket.
