### ISSUE TITLE
Force output path in wget fetch-params.sh

### ISSUE THREAD

**Issue by defuse** [Electric-Coin-Company/zcash#668]
This bug report comes from `@nuttycom` on Twitter:

https://twitter.com/nuttycom/status/691101397618524160

Somehow they made wget download to a `.1` file. Set the download path explicitly and turn on whatever option force-overwrites it.

(It's also possible that the symptom was caused by the check for the file's existence not noticing the file was already there... I think wget appends a .1 if it already exists).

**Comment by nathan-at-least** [comment]
It may have been a race condition?  Also, as of PR #660 the local download path is different and the ``--continue`` option is given, so my hunch is that this is no longer an issue.

**Comment by defuse** [comment]
Huh. I don't see how the `.1` could have arisen in the current script? We pass `--output-document=` to wget so it should never do that.

**Comment by defuse** [comment]
Oh, that was only added on Jan 22.

**Comment by defuse** [comment]
Yeah this is no longer an issue and I opened PR #687 to remove the sed thing and remove the cwd assumption. Closing.
