### ISSUE TITLE
IRC Topic: add FAQ and issue tracker links.

### ISSUE THREAD

**Issue by nathan-at-least** [Electric-Coin-Company/zcash#669]
I'd like to update the ``#zcash`` irc channel topic to link to our FAQ and to our issue tracker in order to improve chances that users file ticket there.

**Comment by defuse** [comment]
@ebfull I assigned you to this since you have the privileges to do that. Either do that or give `earthrise` the ability to do that and then I'll do it.

**Comment by ebfull** [comment]
Done!
