### ISSUE TITLE
zcash daemon has single connection (logs show attempts to peer with tor nodes)

### ISSUE THREAD

**Issue by djpnewton** [Electric-Coin-Company/zcash#673]
After running a few days I only ever connect to the alphatestnet.z.cash peer

The log contains lots of these:

```
2016-01-26 22:51:56 Cannot connect to i6y6ivorwakd7nw3.onion:18333: unsupported
network
```

**Comment by ebfull** [comment]
Closing as duplicate of #651.

**Comment by djpnewton** [comment]
Will solving the attempted onion connections solve the single peer issue too?

**Comment by ebfull** [comment]
There may not be a lot of users connected to the testnet node, or they may be configured to only connect to the testnet node.

**Comment by djpnewton** [comment]
I guess so, seems odd, the difficulty went up, someones producing blocks. why are they hiding =)
