### ISSUE TITLE
Zips: four independent PRFs

### ISSUE THREAD

**Issue by defuse** [Electric-Coin-Company/zcash#675]
Make it say there are *four* PRFs with the last one  like "... where i in {0, 1}" so that it represents two.

**Comment by daira** [comment]
It might be simpler to keep describing it as three PRFs but change the notation to (as closely as I can render it on github) PRF<sup>pk</sup><sub>a<sub>sk</sub></sub>(<em>i</em>, hSig) -- i.e. make <em>i</em> more clearly an input. Note that I generalised other stuff in the doc for arbitrary N<sup>old</sup>, so the number of PRFs if described the other way is 2+N<sup>old</sup>.

**Comment by daira** [comment]
Fixed in https://github.com/Electric-Coin-Company/zips/commit/592c06c26396beab757ba9b5b74117b172c15d85 .
