### ISSUE TITLE
can Pours be selectively dropped from a CTransaction?

### ISSUE THREAD

**Issue by daira** [Electric-Coin-Company/zcash#711]
If an attacker were able to selectively drop some Pours from a CTransaction and submit a modified CTransaction with the remaining Pours, then they could cause some mischief. (The remaining Pours would have to satisfy anchor validity.)

Note that in the absence of chained Pours, a Pour anchor can only refer to the final treestate of a block, which remains valid in any blockchain view containing that block. However, in the potential attack described above, any dropped Pours referring to an intermediate treestate would no longer be valid at all, and so could not be resubmitted without reproving them.

Whether this attack is possible depends on how Pours are bound to the enclosing CTransaction.

**Comment by ebfull** [comment]
The point of #529 is so that pours are bound to the entire rest of the transaction (modulo signatures).
